version: '3'

services:
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8081:8025"
  mysqlDev:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Multitudo
      TZ: Europe/Warsaw
    ports:
      - 3306:3306
  PHPMyAdmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysqlDev:db
    ports:
      - 81:80
  symfony:
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - mysqlDev:db
    ports:
      - 80:80
    env_file:
      - .env
    volumes:
      - ./:/var/www/html