App\DTO\Form\ProjectEditDTO:
  properties:
    domain:
      - NotBlank:
          message: Domena projektu nie moze byc pusta

    client:
      - NotBlank:
          message: Klient projektu nie może być pusty

    type:
      - NotBlank:
          message: Typ projektu nie może być pusty
    links:
      - Url:
          message: Wprowadź poprawny adres URL



